### ISSUE TITLE
Parser does not support named arguments

### ISSUE THREAD

**Issue by nikololiahim** [polystat/odin#17]
The following example from [the paper](https://arxiv.org/pdf/2111.13384.pdf) is not recognized by the parser:
```
distance.
  point
    5:x
    -3:y
  point:to
    13:x
    3.9:y
```

**Comment by fizruk** [comment]
I think J2EO and C2EO do not rely on named arguments, so we can, probably, ignore this syntaxes safely.
@Leosimetti please update documentation of `odin`, mentioning that we do not support this syntax.
When documentation is updated, we can close this issue.
